name: Github Package

on:
  workflow call

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

  jobs:
    bide:
      run_on: ubuntu-latest
      steps:
        - name: Checkout
          uses: action/checkout@v3

        - name: Registry Login
          uses: docker/login-action@v3
          with:
            registry: ${{env.REGISTRY}}
            username: ${{github.actor}}
            password: ${{secrets.BIDE_PAT}}

        - name: Build and push to GH Package
          uses: docker/build-push-action@v4
          with:
            context: backend
            push: true
            tags : ${{env.REGISTRY}}/${{github.actor}}/back-ausecours:late
